# source : https://www.youtube.com/watch?v=3E17mz-6NnE&list=LL&index=14&t=669s
# source : https://www.youtube.com/watch?v=yWNUu7zHW6g&list=LL&index=10&t=712s
# source : https://github.com/mjstealey/wordpress-nginx-docker
version: '3.3'
services:
    wordpress:
        build:
          context: ./requirements/wordpress/
          args:
            PHP_VERSION: ${PHP_VERSION}
        container_name: wordpress
        depends_on:
          - mariadb
        networks:
          - network_42
        env_file:
          - ".env"
        volumes:
          - "wp:/var/www/html/wordpress"
        restart: always

    nginx:
        image: nginx:mine
        build:
          context: ./requirements/nginx/
          args:
            DOMAIN_NAME: ${DOMAIN_NAME}
            LOGIN: ${LOGIN}
        container_name: nginx
        depends_on:
          - wordpress
        networks:
          - network_42
        ports:
          - "443:443"
        volumes:
          - "wp:/var/www/html/wordpress"
          - "lg:/var/log/nginx"
        restart: always

    mariadb:
        env_file:
        - ".env"
        build: ./requirements/mariadb/
        container_name: mariadb
        networks:
        - network_42
        volumes:
        - "db:/var/lib/mysql"
        restart: always

    redis:
        build: ./requirements/bonus/redis/
        container_name: redis
        env_file:
        - ".env"
        environment:
            REDIS_PWD: ${REDIS_PWD}
        networks:
        - network_42
        ports:
        - "6379:6379"
        restart: always


networks:
  network_42:

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_FOLDER}/${WP_FOLDER}
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_FOLDER}/${DB_FOLDER}
      o: bind
  lg:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_FOLDER}/${LG_FOLDER}
      o: bind
